//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceSiteEntities1 : DbContext
    {
        public FinanceSiteEntities1()
            : base("name=FinanceSiteEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chart> Charts { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Earning> Earnings { get; set; }
        public virtual DbSet<Equity> Equities { get; set; }
        public virtual DbSet<Financial> Financials { get; set; }
        public virtual DbSet<Lifestyle> Lifestyles { get; set; }
        public virtual DbSet<LifestylePortfolio> LifestylePortfolios { get; set; }
        public virtual DbSet<PortfolioStock> PortfolioStocks { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<StockHistory> StockHistories { get; set; }
        public virtual DbSet<Symbol> Symbol { get; set; }
        public virtual DbSet<UserStock> UserStocks { get; set; }
    }
}
